### ISSUE TITLE
feature: add search functionality

### ISSUE THREAD

**Issue by Huilensolis** [Huilensolis/Pictura#47]
- [ ] Add search page
- [ ] Add a search input and use the hook useDebouncedValue.
- [ ] Make the change of the value on the input change the URL "search" query.
- [ ] Using the supabase client, which you can get with the hook "useSupabase", fetch the posts from the table "posts" where the "title" equals the search query value and order it by the most recent to the oldest post.
- [ ] display the images in a grid. take how it is done in the `src/app/(site)/app/profile/[username]/page.tsx`  as an example.

**Comment by Jes015** [comment]
i take the issue <3.

**Comment by Huilensolis** [comment]
by the way, we don't have a component for rendering posts yet, so feel free to copy the code from the posts section on `src/app/(site)/app/profile/[username]/page.tsx`  and re[use it.
