### ISSUE TITLE
fix: new post box breaks if the user has no profile picture

### ISSUE THREAD

**Issue by Huilensolis** [Huilensolis/Pictura#51]

**Comment by avi-l** [comment]
Hey i'd be happy to work on more of these bugs if you can get me the .env details. I've tried setting up my own supabase db for this but not interested in manually creating all these tables/rows/etc.

**Comment by Huilensolis** [comment]
hi @avi-l , do you have discord, or any other private site where i could send you the keys?

**Comment by avi-l** [comment]
> hi @avi-l , do you have discord, or any other private site where i could send you the keys?

@disc0rd_name on discord

**Comment by Huilensolis** [comment]
> > hi @avi-l , do you have discord, or any other private site where i could send you the keys?
> 
> @disc0rd_name on discord

I have sent you a friend request. my username is Huilen

**Comment by avi-l** [comment]
can you be more specific about this issue? I created a post without having a profile picture, did not see any errors.

**Comment by Huilensolis** [comment]
hi, the problem was that if you had not a profile picture, the new post box would not show an icon of a profile without a picture.

this gets solved with #91 , where I do a re-design and I include the profile picture on the new post box.
