### ISSUE TITLE
feat: add share option to post options

### ISSUE THREAD

**Issue by Huilensolis** [Huilensolis/Pictura#58]
- [ ] Add  option to share it on Twitter
- [ ] Add option to share it on Linkedin
- [ ] Add option to copy the link to the clipboard

**Comment by avi-l** [comment]
will do.

**Comment by avi-l** [comment]
https://github.com/Huilensolis/Pictura/pull/88

UI is up to you, just created a basic reusable modal and added react-share buttons, and added react-toastify for toast messages

**Comment by Huilensolis** [comment]
as long as it follows the general application UI, I don't have any problem.
